import { Trip, Lead, SiteSettings, Reservation } from '@/types';

export const initialSettings: SiteSettings = {
  agencyName: 'Rutas del Alma Viajes',
  logoUrl: '',
  whatsappNumber: '5491100000000',
  whatsappDisplay: '+54 9 11 0000-0000',
  contactEmail: 'hola@rutasdelalma.demo',
  notificationEmail: 'admin@rutasdelalma.demo',
  instagramUrl: 'https://www.instagram.com/rutasdelalma.demo/',
  facebookUrl: 'https://www.facebook.com/rutasdelalmaviajes/',
  address: 'Buenos Aires, Argentina',
  heroTitle: 'Viajes boutique para descubrir el mundo con calma, compania y asesoramiento real.',
  heroSubtitle:
    'Experiencias grupales curadas para personas que quieren viajar acompanadas, sentirse cuidadas y volver con historias para contar.',
  defaultCurrency: 'USD',
};

export const initialTrips: Trip[] = [
  {
    id: 'trip-patagonia-2027',
    slug: 'patagonia-2027',
    title: 'Patagonia Esencial: Lagos, Glaciares y Montanas',
    destinationCountry: 'Argentina',
    destinationCities: 'Bariloche, El Calafate, El Chalten',
    shortDescription:
      'Una travesia escenica por algunos de los paisajes mas imponentes del sur argentino, combinando naturaleza, caminatas suaves y experiencias gastronomicas.',
    fullDescription:
      'Patagonia Esencial combina lagos de montana, glaciares, bosques, miradores y pequenos pueblos del sur. Es una propuesta ideal para quienes buscan naturaleza, fotografia, buena hoteleria y un ritmo cuidado, con tiempo libre y acompanamiento permanente.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1517824806704-9040b037703b?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1517824806704-9040b037703b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1521292270410-a8c4d716d518?auto=format&fit=crop&w=1200&q=80',
    ],
    startDate: '2027-03-14',
    endDate: '2027-03-22',
    durationDays: 9,
    startCity: 'Bariloche',
    endCity: 'El Calafate',
    intensity: 'Baja a moderada',
    recommendedAge: 'Todas las edades',
    modality: 'Grupal con coordinacion y excursiones seleccionadas',
    currency: 'USD',
    spotsTotal: 14,
    spotsAvailable: 6,
    isFeatured: true,
    isLimitedSpots: true,
    isSoldOut: false,
    isPublished: true,
    includedServices: [
      'Alojamiento en hoteles seleccionados con desayuno',
      'Traslados internos segun programa',
      'Excursion panoramica por lagos y miradores',
      'Visita al Glaciar Perito Moreno',
      'Caminata suave en El Chalten con guia local',
      'Coordinacion durante todo el viaje',
    ],
    notIncludedServices: [
      'Vuelos o buses de llegada y regreso',
      'Comidas no mencionadas',
      'Entradas a parques nacionales',
      'Seguro de asistencia al viajero',
      'Gastos personales y propinas',
      'Servicios no especificados',
    ],
    requirements:
      'Documento vigente, calzado comodo y abrigo por capas. No requiere experiencia previa en trekking.',
    paymentMethods: 'Consultar formas de reserva y financiacion disponibles.',
    observations: 'Grupo reducido para mantener una experiencia tranquila y personalizada.',
    createdAt: '2026-09-20T12:00:00Z',
    updatedAt: '2026-09-20T12:00:00Z',
    itineraryDays: [
      {
        id: 'patagonia-day-1',
        tripId: 'trip-patagonia-2027',
        dayNumber: 1,
        title: 'Llegada a Bariloche',
        description:
          'Recepcion, traslado al hotel y primer encuentro del grupo. Tarde libre para caminar por el centro civico y disfrutar las vistas del lago Nahuel Huapi.',
      },
      {
        id: 'patagonia-day-2',
        tripId: 'trip-patagonia-2027',
        dayNumber: 2,
        title: 'Circuito de lagos y miradores',
        description:
          'Recorrido panoramico por los puntos mas emblematicos de Bariloche, con paradas para fotos, cafe y tiempo libre junto al lago.',
      },
      {
        id: 'patagonia-day-3',
        tripId: 'trip-patagonia-2027',
        dayNumber: 3,
        title: 'Vuelo o traslado hacia El Calafate',
        description:
          'Traslado hacia El Calafate, instalacion en el hotel y caminata por el pueblo para conocer su ambiente patagonico.',
      },
      {
        id: 'patagonia-day-4',
        tripId: 'trip-patagonia-2027',
        dayNumber: 4,
        title: 'Glaciar Perito Moreno',
        description:
          'Dia completo para admirar el glaciar desde sus pasarelas y vivir una de las postales mas impactantes de la Patagonia.',
      },
      {
        id: 'patagonia-day-5',
        tripId: 'trip-patagonia-2027',
        dayNumber: 5,
        title: 'El Chalten y senderos suaves',
        description:
          'Salida hacia El Chalten con caminata interpretativa de baja dificultad, ideal para conectar con el paisaje sin apuros.',
      },
    ],
  },
  {
    id: 'trip-marruecos-2027',
    slug: 'marruecos-2027',
    title: 'Marruecos Sensorial: Medinas, Desierto y Riads',
    destinationCountry: 'Marruecos',
    destinationCities: 'Marrakech, Ait Ben Haddou, Merzouga, Fez',
    shortDescription:
      'Un recorrido boutique por mercados, kasbahs, dunas y ciudades historicas, pensado para vivir Marruecos con acompanamiento y mucho encanto.',
    fullDescription:
      'Marruecos Sensorial es una experiencia para quienes quieren descubrir medinas vibrantes, dormir en riads con encanto, contemplar el Sahara y conocer la cultura local de manera cuidada. Una ruta visual, aromatica y profundamente memorable.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1548018560-c7196548e84d?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1548018560-c7196548e84d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1528657249085-c569d3a2de9e?auto=format&fit=crop&w=1200&q=80',
    ],
    startDate: '2027-05-06',
    endDate: '2027-05-16',
    durationDays: 11,
    startCity: 'Marrakech',
    endCity: 'Fez',
    intensity: 'Moderada',
    recommendedAge: 'Adultos',
    modality: 'Ruta acompanada con guias locales',
    currency: 'USD',
    spotsTotal: 12,
    spotsAvailable: 5,
    isFeatured: true,
    isLimitedSpots: true,
    isSoldOut: false,
    isPublished: true,
    includedServices: [
      'Alojamiento en riads y hoteles seleccionados',
      'Desayunos diarios y cenas indicadas',
      'Traslados internos en vehiculo privado',
      'Noche en campamento en el desierto',
      'Guias locales en ciudades principales',
      'Coordinacion durante todo el viaje',
    ],
    notIncludedServices: [
      'Vuelos internacionales',
      'Comidas no mencionadas',
      'Bebidas y gastos personales',
      'Seguro de asistencia al viajero',
      'Propinas y actividades opcionales',
      'Servicios no especificados',
    ],
    requirements:
      'Pasaporte vigente y predisposicion para caminar por medinas con calles irregulares.',
    paymentMethods: 'Consultar condiciones de reserva y opciones de pago.',
    observations: 'Experiencia pensada para grupos pequenos y atencion personalizada.',
    createdAt: '2026-09-20T12:00:00Z',
    updatedAt: '2026-09-20T12:00:00Z',
    itineraryDays: [
      {
        id: 'marruecos-day-1',
        tripId: 'trip-marruecos-2027',
        dayNumber: 1,
        title: 'Bienvenida en Marrakech',
        description:
          'Llegada, traslado al riad y primer paseo por los alrededores para empezar a descubrir colores, aromas y sabores marroquies.',
      },
      {
        id: 'marruecos-day-2',
        tripId: 'trip-marruecos-2027',
        dayNumber: 2,
        title: 'Medina, palacios y zocos',
        description:
          'Recorrido guiado por Marrakech, sus patios, palacios, jardines y zocos, con tiempo para disfrutar un te de menta.',
      },
      {
        id: 'marruecos-day-3',
        tripId: 'trip-marruecos-2027',
        dayNumber: 3,
        title: 'Ruta hacia el desierto',
        description:
          'Salida atravesando paisajes montanosos y pueblos de adobe hasta acercarnos a las puertas del Sahara.',
      },
      {
        id: 'marruecos-day-4',
        tripId: 'trip-marruecos-2027',
        dayNumber: 4,
        title: 'Dunas de Merzouga',
        description:
          'Atardecer entre dunas, cena y noche en campamento, una de las experiencias mas especiales del viaje.',
      },
    ],
  },
  {
    id: 'trip-grecia-2027',
    slug: 'grecia-2027',
    title: 'Grecia Azul: Atenas, Islas y Atardeceres',
    destinationCountry: 'Grecia',
    destinationCities: 'Atenas, Paros, Naxos, Santorini',
    shortDescription:
      'Una propuesta mediterranea para combinar historia, mar, pueblos blancos, gastronomia y dias tranquilos en islas griegas.',
    fullDescription:
      'Grecia Azul invita a descubrir la historia de Atenas y la belleza de las islas Cicladas con un ritmo relajado. Ideal para viajeros que buscan cultura, mar, pequenos hoteles con encanto y tiempo libre para disfrutar.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1600&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80',
    ],
    startDate: '2027-09-09',
    endDate: '2027-09-19',
    durationDays: 11,
    startCity: 'Atenas',
    endCity: 'Santorini',
    intensity: 'Baja',
    recommendedAge: 'Todas las edades',
    modality: 'Grupal con coordinacion y tiempo libre',
    currency: 'USD',
    spotsTotal: 14,
    spotsAvailable: 9,
    isFeatured: true,
    isLimitedSpots: true,
    isSoldOut: false,
    isPublished: true,
    includedServices: [
      'Hoteles boutique con desayuno',
      'Ferries internos entre islas',
      'Visita guiada por Atenas historica',
      'Coordinacion y asistencia durante la ruta',
      'Recomendaciones personalizadas de playas y restaurantes',
      'Encuentro de bienvenida y cierre del viaje',
    ],
    notIncludedServices: [
      'Vuelos internacionales',
      'Comidas no mencionadas',
      'Traslados no especificados',
      'Seguro de asistencia al viajero',
      'Gastos personales',
      'Actividades opcionales',
    ],
    requirements: 'Pasaporte vigente y ganas de disfrutar el Mediterraneo sin correr.',
    paymentMethods: 'Consultar alternativas de reserva y pago.',
    observations: 'Itinerario flexible para combinar visitas sugeridas y tiempo libre.',
    createdAt: '2026-09-20T12:00:00Z',
    updatedAt: '2026-09-20T12:00:00Z',
    itineraryDays: [
      {
        id: 'grecia-day-1',
        tripId: 'trip-grecia-2027',
        dayNumber: 1,
        title: 'Llegada a Atenas',
        description:
          'Recepcion, traslado al hotel y encuentro del grupo para presentar la ruta y disfrutar la primera cena sugerida.',
      },
      {
        id: 'grecia-day-2',
        tripId: 'trip-grecia-2027',
        dayNumber: 2,
        title: 'Atenas historica',
        description:
          'Visita guiada por los puntos mas representativos de la ciudad y tiempo libre para caminar por Plaka.',
      },
      {
        id: 'grecia-day-3',
        tripId: 'trip-grecia-2027',
        dayNumber: 3,
        title: 'Ferry a Paros',
        description:
          'Traslado al puerto y viaje hacia Paros. Tarde libre para conocer el pueblo y disfrutar el mar.',
      },
      {
        id: 'grecia-day-4',
        tripId: 'trip-grecia-2027',
        dayNumber: 4,
        title: 'Playas y pueblos blancos',
        description:
          'Dia para recorrer rincones costeros, pequenas callecitas y miradores con ritmo tranquilo.',
      },
    ],
  },
];

export const initialLeads: Lead[] = [
  {
    id: 'lead-demo-001',
    tripId: 'trip-patagonia-2027',
    tripName: 'Patagonia Esencial: Lagos, Glaciares y Montanas',
    fullName: 'Lucia Fernandez',
    email: 'lucia.demo@example.com',
    phone: '+5491100001111',
    city: 'Rosario',
    passengersCount: 2,
    age: '41',
    attractionReason: 'Naturaleza, fotografia y viajar con acompanamiento',
    concernReason: 'El clima y la dificultad de las caminatas',
    stage: 'Estoy evaluando seriamente viajar',
    message: 'Quiero viajar con mi hermana. Nos interesa saber fechas y nivel de caminata.',
    status: 'Nuevo',
    origin: 'Patagonia 2027',
    utmSource: 'instagram',
    utmMedium: 'organic',
    utmCampaign: 'demo_patagonia',
    createdAt: '2026-09-21T14:30:00Z',
    updatedAt: '2026-09-21T14:30:00Z',
    notes: [
      {
        id: 'note-demo-001',
        leadId: 'lead-demo-001',
        content: 'Lead demo: interesada en viajar con una acompananate.',
        createdAt: '2026-09-21T15:00:00Z',
      },
    ],
  },
  {
    id: 'lead-demo-002',
    tripId: 'trip-marruecos-2027',
    tripName: 'Marruecos Sensorial: Medinas, Desierto y Riads',
    fullName: 'Marcos Alvarez',
    email: 'marcos.demo@example.com',
    phone: '+5491100002222',
    city: 'Buenos Aires',
    passengersCount: 1,
    age: '52',
    attractionReason: 'Dormir en el desierto y conocer Marrakech',
    concernReason: 'Viajar solo por primera vez',
    stage: 'Quiero reservar',
    message: 'Me interesa recibir el programa completo y condiciones de reserva.',
    status: 'Interesado',
    origin: 'Marruecos 2027',
    utmSource: 'google',
    utmMedium: 'search',
    utmCampaign: 'demo_marruecos',
    createdAt: '2026-09-22T10:15:00Z',
    updatedAt: '2026-09-22T12:00:00Z',
    notes: [
      {
        id: 'note-demo-002',
        leadId: 'lead-demo-002',
        content: 'Lead demo: enviar detalles de cupos y alojamiento.',
        createdAt: '2026-09-22T12:00:00Z',
      },
    ],
  },
];

export const initialReservations: Reservation[] = [
  {
    id: 'res-demo-001',
    leadId: 'lead-demo-002',
    tripId: 'trip-marruecos-2027',
    tripName: 'Marruecos Sensorial: Medinas, Desierto y Riads',
    passengerName: 'Marcos Alvarez',
    passengersCount: 1,
    totalAmount: 0,
    depositAmount: 0,
    pendingBalance: 0,
    currency: 'USD',
    status: 'Pendiente',
    notes: 'Reserva demo sin importes reales cargados.',
    reservationDate: '2026-09-22T13:00:00Z',
  },
];
